# Generated by Django 4.1.13 on 2023-12-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="danceClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(default="assets\\", upload_to="classes")),
                ("description", models.TextField()),
                ("startDate", models.DateField()),
                ("duration", models.CharField(max_length=10)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(default="assets\\", upload_to="events")),
                ("date", models.DateField()),
                ("location", models.TextField()),
                ("ticketPrice", models.IntegerField()),
            ],
        ),
    ]
