# Generated by Django 4.1.13 on 2023-12-07 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dancersite", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="danceClass",
            new_name="danceClasse",
        ),
    ]
